"""Add documents table

Revision ID: 1464d3141fcd
Revises: 1fb9bc43c141
Create Date: 2025-02-11 18:26:50.232389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1464d3141fcd'
down_revision: Union[str, None] = '1fb9bc43c141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('document_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'conversations', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'document_id')
    # ### end Alembic commands ###
