"""Add file_path to documents

Revision ID: 23d1e835e313
Revises: 89af09a3a402
Create Date: 2025-02-07 17:38:00.601021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d1e835e313'
down_revision: Union[str, None] = '89af09a3a402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.String(), nullable=True))
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###
