"""add_teacher_conversations_relationship

Revision ID: 2bf91dd235ce
Revises: 98ff6e98b78f
Create Date: 2025-04-17 12:43:54.844247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf91dd235ce'
down_revision: Union[str, None] = '98ff6e98b78f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.alter_column('conversations', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'conversations', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.alter_column('conversations', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('conversations', 'teacher_id')
    # ### end Alembic commands ###
