"""add_topic_model

Revision ID: 357ec212f9b8
Revises: unify_user_models
Create Date: 2025-05-10 18:36:15.212689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357ec212f9b8'
down_revision: Union[str, None] = 'unify_user_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # La tabla topics ya existe, así que no necesitamos crearla de nuevo
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No necesitamos hacer nada en el downgrade ya que no hicimos cambios en el upgrade
    pass
    # ### end Alembic commands ###