"""add_images_and_update_messages

Revision ID: 9abdb3412878
Revises: 6ce82d78750c
Create Date: 2025-05-24 21:12:36.273836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9abdb3412878'
down_revision: Union[str, None] = '6ce82d78750c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.drop_constraint('conversations_document_id_fkey', 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'document_id')
    op.add_column('messages', sa.Column('image_id', sa.Integer(), nullable=True))
    op.alter_column('messages', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'messages', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'image_id')
    op.add_column('conversations', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('conversations_document_id_fkey', 'conversations', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###