"""add_summary_column_to_subjects

Revision ID: f3d386bd801a
Revises: 9dda3660056d
Create Date: 2025-06-04 09:26:41.570201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d386bd801a'
down_revision: Union[str, None] = '9dda3660056d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'summary')
    # ### end Alembic commands ###